apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-two
spec:
  selector:
    matchLabels:
      app: myapp-two
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-two
    spec:
      containers:
      - name: myapp-two
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
